### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by nkaeming** [AvonHaaren/ec-sim#1]
Hi all,

thank you for sharing the code.

We try to build it with gcc 9.2.0 Ubuntu 18.04. Unfortunately we get a lot of errors using make.

Do you have a hint what build configuration we can use to get it working?

Best wishes,
Niklas

**Comment by AvonHaaren** [comment]
I compiled this with Visual Studio and XCode, so I didn't update the makefile, my bad. 
You have to use -std=c++2a because I am using a lot of C++ 2017 and 2020 features.

However, since I'm still on a Mac, I can only test this with the g++ compiler packaged with Apple clang.

**Comment by nkaeming** [comment]
Thanks a lot. Most of the errors are gone :). It seems there is some trouble with the ARM Processor in our case, but we can fix it I guess.
